### ISSUE TITLE
Review issue: functionality

### ISSUE THREAD

**Issue by andytwoods** [davekinkead/reasons#2]
As per https://github.com/openjournals/joss-reviews/issues/1044 Functionality, functionality.

on windows, in chrome, I couldn't undo via control-z.

**Comment by davekinkead** [comment]
Thanks for the bug report @andytwoods 

I can't reproduce the problem on my setup but the relevant code is here https://github.com/davekinkead/reasons/blob/3c063b76f9f6c6e28137833cd43a38e10bf1b9f9/lib/ui.js#L138-L140

`Cmd + z`, `Ctrl + z`, or the `browser specific metakey + z` should all work.  I'll try to find a windows machine with chrome shortly.
 
In the mean time, can you please try the following http://www.reasons.io/maps/e25636f to see if the issue is browser or environment caused.

**Comment by davekinkead** [comment]
@andytwoods could you also please visit https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey and see if you can get `metaKey = true` in the [example](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey#Example)

**Comment by andytwoods** [comment]
I'm a reviewer for your submission to joss. I don't use your software. Not sure it's fair I am also involved in the debug process. Just use VirtualBox to check out the issue?

**Comment by davekinkead** [comment]
Quick update - I'm currently at a few conferences and will address this later this month when I'm back

**Comment by davekinkead** [comment]
Sorry for the delay. I was unable to reproduce the issue on a VirtualBox and have only just had access to a windows machine. `ctrl z` and `ctrl y` now work and I've manually tested windows 10 + chrome & windows 10 + firefox.
